#!/bin/bash
#PBS -N varDirTest
#PBS -j oe
#PBS -o /mnt/lfs/walt2178/Projects/rna-pipeline-python-qsub-staging/results/newoutput.log
#PBS -d /mnt/lfs/walt2178/Projects/rna-pipeline-python-qsub-staging/bin/perl
#PBS -v FOO="/mnt/lfs/walt2178/Projects/rna-pipeline-python-qsub-staging/bin/bash",SOMETHING="Danger Zone!"
echo "PBS_O_HOST: $PBS_O_HOST"
echo "PBS_SERVER: $PBS_SERVER"
echo "PBS_O_QUEUE: $PBS_O_QUEUE"
echo "PBS_O_HOME: $PBS_O_HOME || $HOME"
echo "PBS_O_WORKDIR: $PBS_O_WORKDIR"
echo "PBS_O_INITDIR: $PBS_O_INITDIR"
echo "PBS_ARRAYID: $PBS_ARRAYID"
echo "PBS_ENVIRONMENT: $PBS_ENVIRONMENT"
echo "PBS_JOBID: $PBS_JOBID"
echo "PBS_JOBNAME: $PBS_JOBNAME"
echo "PBS_NODEFILE: $PBS_NODEFILE"
echo "PBS_QUEUE: $PBS_QUEUE"

echo "FOO: $FOO"
#echo "BAR: $BAR"
echo "Something something...$SOMETHING"
date